name: Bug report
description: Report a bug
title: "bug: "
labels: ["type:bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: Repro steps
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python, device, etc.
    validations:
      required: false
